### ISSUE TITLE
Error while running the inference.py

### ISSUE THREAD

**Issue by saivineethkumar** [Linardos/SalEMA#3]
Hi @Linardos 
I am trying to run the inference.py file for UCF data and I got the following error, can you please tell me what is the problem..

I run the following command  `python inference.py -dataset=UCF-sports -pt_model=/home/dsvk/MTP1/SalEMA/SalEMA30.pt -alpha=0.1 -dst=/home/dsvk/MTP1/SalEMA/data/UCF-sports/testing -src=/home/dsvk/MTP1/SalEMA/data/UCF-sports/testing`

I get the following:

> Output directory /home/dsvk/MTP1/SalEMA/data/UCF-sports/testing
> Commencing inference for dataset UCF-sports
> Size of test set is 47
> Model initialized, EMA located at Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
> Pre-trained model /home/dsvk/MTP1/SalEMA/SalEMA30.pt loaded succesfully
> Alpha tuned to tensor([0.1000])
> Be warned, you are about to write on an existing folder /home/dsvk/MTP1/SalEMA/data/UCF-sports/testing. If this is not intentional cancel now.
> Destination: /home/dsvk/MTP1/SalEMA/SalEMA30_predictions
> The final destination is /home/dsvk/MTP1/SalEMA/SalEMA30_predictions/Diving-Side-0000001.png. Cancel now if this is incorrect
> Traceback (most recent call last):
>   File "inference.py", line 302, in <module>
>     main(args)
>   File "inference.py", line 230, in main
>     state, saliency_map = model.forward(input_ = clip[idx], prev_state = state)
>   File "/home/dsvk/MTP1/SalEMA/src/model/SalEMA.py", line 108, in forward
>     current_state = sigmoid(self.alpha)*self.salgan[self.ema_loc](x)+(1-sigmoid(self.alpha))*prev_state
> RuntimeError: expected device cpu and dtype Float but got device cuda:0 and dtype Float

My Cuda and torch versions are:
cuda:  9.2, V9.2.148
torch : 1.2.0 
torchvision : 0.4.0a0+9232c4a

**Comment by Linardos** [comment]
Hm, I just tried running on UCF with the github version of the code and it works normally, doesn't produce that error for me. **The only difference I can see is that my cuda is 8.0 so the issue is definitely related to that.** 

It seems like the error happens after the first step : 
```
File "/home/dsvk/MTP1/SalEMA/src/model/SalEMA.py", line 108, in forward
current_state = sigmoid(self.alpha)*self.salganself.ema_loc+(1-sigmoid(self.alpha))*prev_state
RuntimeError: expected device cpu and dtype Float but got device cuda:0 and dtype Float
```
After the first step the only thing that is different is that the model is using information from the past. That makes me think that whatever the core of the issue, it must be related to the **state**/**prev_state** variable.

It looks like some variable is not mapped to CUDA in your case. It is more likely that this variable is the **state** but I'd suggest you play around to find out.

**Comment by dalind** [comment]
The problem seems to be that the sigmoid function returns a cpu Float instead of a cuda Float.

Either change the line 
`current_state = sigmoid(self.alpha)*self.salgan[self.ema_loc](x)+(1-sigmoid(self.alpha))`
to:
`current_state = torch.sigmoid(self.alpha).cuda() * self.salgan[self.ema_loc](x) + (1 - torch.sigmoid(self.alpha).cuda())`

or the following line somewhere, e.g., in the main method before inferencer.py before the data loader:
`torch.set_default_tensor_type('torch.cuda.FloatTensor')`

**Comment by Linardos** [comment]
Noted, I updated the line so that when use_gpu is True it explicitly moves sigmoid output to cuda.
I can only imagine this happened during some PyTorch update as I didn't have that issue before.
